# Generated by Django 4.1.5 on 2024-06-04 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(default='', max_length=100)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('script_name', models.TextField(blank=True, null=True)),
                ('path', models.CharField(max_length=500)),
                ('wdgi_multithread', models.BooleanField(default=False)),
                ('wdgi_multiprocess', models.BooleanField(default=False)),
                ('remote_addr', models.CharField(blank=True, max_length=999, null=True)),
                ('remote_host', models.CharField(blank=True, max_length=999, null=True)),
                ('remote_port', models.CharField(blank=True, max_length=100, null=True)),
                ('server_name', models.CharField(blank=True, max_length=999, null=True)),
                ('server_port', models.CharField(blank=True, max_length=100, null=True)),
                ('http_host', models.CharField(blank=True, max_length=999, null=True)),
                ('http_connection', models.CharField(blank=True, max_length=999, null=True)),
                ('http_cache_control', models.CharField(blank=True, max_length=999, null=True)),
                ('http_sec_ch_ua', models.TextField(blank=True, null=True)),
                ('http_sec_ch_ua_mobile', models.CharField(blank=True, max_length=999, null=True)),
                ('http_sec_ch_ua_platform', models.CharField(blank=True, max_length=999, null=True)),
                ('http_user_agent', models.CharField(blank=True, max_length=999, null=True)),
                ('http_accept', models.CharField(blank=True, max_length=999, null=True)),
                ('post_data', models.TextField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('data', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
