# Generated by Django 4.1.5 on 2024-06-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestlog',
            name='real_ip',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
