# Generated by Django 4.1.5 on 2024-06-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_userrequestlog_real_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestlog',
            name='log_requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
