# Generated by Django 4.1.5 on 2024-07-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0003_userrequestlog_log_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequestlog',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='http_accept',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='http_cache_control',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='http_connection',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='http_host',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='http_sec_ch_ua',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='http_sec_ch_ua_mobile',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='http_sec_ch_ua_platform',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='http_user_agent',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='post_data',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='remote_addr',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='remote_host',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='remote_port',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='script_name',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='server_port',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='wdgi_multiprocess',
        ),
        migrations.RemoveField(
            model_name='userrequestlog',
            name='wdgi_multithread',
        ),
    ]
