# Generated by Django 4.1.5 on 2024-07-20 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_userrequestlog_geo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.TextField()),
                ('text', models.TextField()),
                ('mask', models.CharField(blank=True, max_length=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sent', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
