# Generated by Django 4.1.5 on 2024-07-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0007_phonemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemessage',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
