# Generated by Django 4.1.5 on 2024-07-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_alter_phonemessage_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemessage',
            name='sms_type',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
