# Generated by Django 4.1.5 on 2024-07-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_phonemessage_sms_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemessage',
            name='sms_type',
            field=models.CharField(blank=True, choices=[('OTP', 'OTP'), ('Appointment', 'Appointment'), ('OnlineAppointment', 'OnlineAppointment')], max_length=999, null=True),
        ),
    ]
