# Generated by Django 4.1.5 on 2024-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0012_smsservicekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsservicekey',
            name='key_provider',
            field=models.CharField(choices=[('Telenor', 'Telenor'), ('Jazz', 'Jazz'), ('Zong', 'Zong')], default='Telenor', max_length=999),
        ),
    ]
