# Generated by Django 4.2.7 on 2025-01-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0015_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=999)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
