# Generated by Django 4.2.7 on 2025-01-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0016_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='emails',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(default='', max_length=999),
        ),
    ]
