# Generated by Django 4.2.7 on 2025-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0017_alter_emaillog_emails_alter_emaillog_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
