# Generated by Django 4.2.7 on 2025-01-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0018_emaillog_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
