# Generated by Django 4.2.7 on 2025-01-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0019_phonemessage_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('urls', models.TextField()),
                ('analytic_type', models.CharField(choices=[('Views', 'Views'), ('Clicks', 'Clicks'), ('Visits', 'Visits')], default='Views', max_length=999)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
