# Generated by Django 4.1.5 on 2025-01-02 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pharmacy', '0005_alter_storelocation_email_alter_storelocation_phone'),
        ('Vendor', '0001_initial'),
        ('Pharmaceutical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=999)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField()),
                ('generic_category', models.CharField(default='', max_length=999)),
                ('formulation', models.CharField(default='', max_length=999)),
                ('strength', models.CharField(default='', max_length=999)),
                ('pack_size', models.CharField(default='', max_length=999)),
                ('prescription_required', models.BooleanField(default=False)),
                ('pack_form', models.CharField(default='', max_length=999)),
                ('key_highlights', models.TextField(default='')),
                ('storage', models.CharField(default='', max_length=999)),
                ('habit_forming', models.CharField(default='', max_length=999)),
                ('sedation', models.CharField(default='', max_length=999)),
                ('child_safety', models.CharField(default='', max_length=999)),
                ('marketed_by', models.CharField(default='', max_length=999)),
                ('route_of_administration', models.CharField(default='', max_length=999)),
                ('Images', models.TextField(default='')),
                ('sku', models.CharField(default='', max_length=999)),
                ('bar_code', models.CharField(default='', max_length=999)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='Product/qr_codes/%Y-%m/')),
                ('slug', models.TextField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('Vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_products', to='Vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=999, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=999, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=999, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=999, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=999, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_sub_categories', to='Product.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0, verbose_name='Discount % : ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_stocks', to='Pharmacy.storelocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stocks', to='Product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_products', to='Product.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_products', to='Pharmaceutical.pharmaceutical'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_form_products', to='Product.productform'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_type_products', to='Product.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Pharmacy.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ManyToManyField(null=True, related_name='sub_category_products', to='Product.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='treatment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_type_products', to='Product.treatmenttype'),
        ),
    ]
