# Generated by Django 4.1.5 on 2025-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_productimage_is_watermark_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Discount % : '),
        ),
    ]
