# Generated by Django 4.1.5 on 2025-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default='', max_length=999),
        ),
    ]
