# Generated by Django 4.1.5 on 2025-01-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_max_order_product_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
    ]
