# Generated by Django 4.1.5 on 2025-01-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Product/SubCategory/%Y-%m'),
        ),
    ]
