# Generated by Django 4.1.5 on 2025-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_treatmenttype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Images',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='child_safety',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='formulation',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_category',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='habit_forming',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='key_highlights',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketed_by',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_form',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='route_of_administration',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sedation',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='strength',
            field=models.CharField(blank=True, default='', max_length=999, null=True),
        ),
    ]
