# Generated by Django 4.1.5 on 2025-01-01 05:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=999)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logo/')),
                ('phone', models.CharField(default='', max_length=999)),
                ('email', models.CharField(default='', max_length=999)),
                ('website', models.TextField(default='')),
                ('slug', models.CharField(default=uuid.uuid4, max_length=999, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_type', models.CharField(choices=[('Profile Image', 'Profile Image'), ('License', 'License')], default='Profile Image', max_length=30)),
                ('file', models.FileField(help_text='Whenever change Image, You must uncheck "Is Watermark Added"', upload_to='PharmacyStore/Files/%Y-%m')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_watermark_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_medias', to='Pharmacy.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=999)),
                ('address', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('lat', models.CharField(default='', max_length=999)),
                ('lng', models.CharField(default='', max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_locations', to='Pharmacy.store')),
            ],
        ),
    ]
