# Generated by Django 4.1.5 on 2025-01-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='logo',
        ),
    ]
