# Generated by Django 4.1.5 on 2025-01-01 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_rename_is_thumbnail_generated_profile_is_watermark_added_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pharmacy', '0002_remove_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='profile_stores', to='Profile.profile'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
