# Generated by Django 4.1.5 on 2025-01-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0014_verificationcode_mobile_number'),
        ('Pharmacy', '0003_store_profile_store_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_pharmacy_locations', to='Trauma.city'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_pharmacy_locations', to='Trauma.country'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_pharmacy_locations', to='Trauma.state'),
        ),
    ]
