# Generated by Django 4.1.5 on 2025-01-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0004_storelocation_city_storelocation_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelocation',
            name='email',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='phone',
            field=models.CharField(default='', max_length=999),
        ),
    ]
