# Generated by Django 4.2.7 on 2025-03-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0005_alter_storelocation_email_alter_storelocation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='PharmacyStore/ProductFiles/%Y-%m')),
                ('file_name', models.CharField(default='', max_length=999)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Pending')),
                ('is_valid_file', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_location_product_files', to='Pharmacy.storelocation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_product_files', to='Pharmacy.store')),
            ],
        ),
    ]
