# Generated by Django 4.2.7 on 2025-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0006_storeproductfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductfile',
            name='file_type',
            field=models.CharField(choices=[('csv', 'csv'), ('excel', 'excel'), ('other', 'other')], default='other', max_length=999),
        ),
        migrations.AlterField(
            model_name='storeproductfile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=999),
        ),
    ]
