# Generated by Django 4.1.5 on 2023-03-24 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='', max_length=500)),
                ('last_name', models.CharField(default='', max_length=500)),
                ('full_name', models.CharField(default='', max_length=800)),
                ('email', models.EmailField(max_length=254)),
                ('profile_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Lab')], default='Patient', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
