# Generated by Django 4.1.5 on 2023-04-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_options_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
