# Generated by Django 4.1.5 on 2023-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Patient', 'General'), ('Doctor', 'Doctor'), ('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Lab')], default='Patient', max_length=15),
        ),
    ]
