# Generated by Django 4.1.5 on 2024-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Hospital', 'Hospital'), ('Pharmacy', 'Pharmacy'), ('Lab', 'Lab'), ('Private_Clinic', 'Private_Clinic')], default='Patient', max_length=15),
        ),
    ]
