# Generated by Django 4.1.5 on 2024-12-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_thumbnail_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', help_text='Whenever change Image, You must uncheck "Is Thumbnail Generated"', upload_to='Patients/Images/%Y-%m'),
        ),
    ]
