# Generated by Django 4.1.5 on 2024-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_profile_is_thumbnail_generated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_thumbnail_generated',
            new_name='is_watermark_added',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='', help_text='Whenever change Image, You must uncheck "Is Watermark Added"', upload_to='Patients/Images/%Y-%m'),
        ),
    ]
