# Generated by Django 4.1.5 on 2025-01-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_rename_is_thumbnail_generated_profile_is_watermark_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
