# Generated by Django 4.1.5 on 2025-01-15 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0009_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=800)),
                ('address', models.TextField(default='')),
                ('country', models.CharField(default='', max_length=800)),
                ('state', models.CharField(default='', max_length=800)),
                ('city', models.CharField(default='', max_length=800)),
                ('postal_code', models.CharField(default='', max_length=800)),
                ('mobile_number', models.CharField(default='', max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
