# Generated by Django 4.1.5 on 2025-01-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_shipingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipingaddress',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
