# Generated by Django 4.1.5 on 2024-06-03 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0014_doctorreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bill', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Booked', max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=999)),
                ('instructions', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('fee', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('service_fee', models.PositiveIntegerField(default=0)),
                ('bill', models.PositiveIntegerField(default=0)),
                ('fee_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=999)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='Cash', max_length=999)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=999)),
                ('appointment_location', models.CharField(choices=[('Online', 'Online'), ('InPerson', 'InPerson')], default='InPerson', max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Appointment.appointmentgroup')),
                ('doct_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doct_hospital_appointments', to='Doctor.doctorwithhospital')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to='Doctor.doctor')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot_appointments', to='Doctor.doctortimeslots')),
            ],
        ),
    ]
