# Generated by Django 4.1.5 on 2024-07-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
