"""
Django settings for TraumaCare project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import environ
import os

from .tc_settings import *
# Build paths inside the project like this: BASE_DIR / 'subdir'.


SETTING_BASE = Path(__file__).resolve().parent
BASE_DIR = SETTING_BASE.parent

env = environ.Env()
environ.Env.read_env(os.path.join(SETTING_BASE , '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
IS_LOCAL_SERVER = env('IS_LOCAL_SERVER') or '1'

DASHBOARD_REDIRECT_URL = env('DASHBOARD_REDIRECT_URL')
# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['traumacare.pk']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_crontab',

    'Trauma.apps.TraumaConfig',
    'Authentication.apps.AuthenticationConfig',
    'Product.apps.ProductConfig',
    'Doctor.apps.DoctorConfig',
    'Hospital.apps.HospitalConfig',
    'Pharmacy.apps.PharmacyConfig',
    'Lab.apps.LabConfig',
    'Appointment.apps.AppointmentConfig',
    'Api.apps.ApiConfig',
    'Profile.apps.ProfileConfig',
    'Medicine.apps.MedicineConfig',
    'Cart.apps.CartConfig',
    'Chat.apps.ChatConfig',
    'ChatXpo.apps.ChatxpoConfig',
    'Secure.apps.SecureConfig',
    'Administration.apps.AdministrationConfig',
    'Blog.apps.BlogConfig',
    'AskDoctor.apps.AskdoctorConfig',
]
GEOIP_PATH =os.path.join('geoip')
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom Milddlewares 
    'TraumaCare.Middlewares.request_data.RequestDataCustomMiddleware',
    'TraumaCare.Middlewares.user_logs_middleware.TrackUserLogMiddleware',
]


CRONJOBS = [
    ('*/15 * * * *', 'Blog.Cronjob.generateBlogPost')
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]


ROOT_URLCONF = 'TraumaCare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'TraumaCare.context_processors.global_context_processor', # Custom Context Processor
                'TraumaCare.context_processors.specialities_context_processor', # Custom Context Processor
                'TraumaCare.context_processors.diseases_context_processor', # Custom Context Processor
                'TraumaCare.context_processors.hospitals_context_processor', # Custom Context Processor
                'TraumaCare.context_processors.appointments_context_processors', # Custom Context Processor
            ],
        },
    },
]

ASGI_APPLICATION = 'TraumaCare.asgi.application'
# WSGI_APPLICATION = 'TraumaCare.wsgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


if IS_LOCAL_SERVER == '0':
    DATABASES = {
        'default': {
            'ENGINE': env('DATABASE_ENGINE'),
            'NAME': env('DATABASE_NAME'),
            'USER': env('DATABASE_USER'),
            'PASSWORD': env('DATABASE_PASSWORD'),
            'HOST': env('DATABASE_HOST'),
            'PORT': env('DATABASE_PORT'),
        }
    }
elif IS_LOCAL_SERVER == '1':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Karachi"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR , 'static')


MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR , 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'Authentication.User'
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES' : [
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES' : [
        'rest_framework.permissions.IsAuthenticated'
    ],
}


# EMAIL SETTINGS 
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "traumacare.pk@gmail.com"
EMAIL_HOST_PASSWORD = "zpsjmfoaipkndfqy"

# CONSTANT VARIABLES 

ACCOUNT_TRAUMACARE_URL=env('ACCOUNT_TRAUMACARE_URL')
THIS_APPLICATION_URL=env('THIS_APPLICATION_URL')


try:
    from .local_settings import *
except:
    pass