# Generated by Django 4.1.5 on 2024-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blogmedia_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
    ]
