# Generated by Django 4.1.5 on 2024-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blogmedia_is_thumbnail_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='image',
            field=models.FileField(default='', upload_to='Blog/Images/%Y-%m'),
        ),
    ]
