# Generated by Django 4.1.5 on 2024-06-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_blogmedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmedia',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='Blog/Images/%Y-%m'),
        ),
    ]
