# Generated by Django 4.1.5 on 2024-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_blogmedia_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmedia',
            name='mini_thumbnail',
            field=models.ImageField(default='', upload_to='Blog/Images/%Y-%m'),
        ),
    ]
