# Generated by Django 4.1.5 on 2024-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_blogmedia_mini_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='gpt_content',
            field=models.TextField(default=''),
        ),
    ]
