# Generated by Django 4.1.5 on 2023-03-05 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('dial_code', models.CharField(blank=True, max_length=5, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('social_account', models.BooleanField(default=False)),
                ('social_platform', models.CharField(blank=True, choices=[('Google', 'Google'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Apple', 'Apple')], max_length=32, null=True)),
                ('social_id', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date Time')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
            options={
                'unique_together': {('dial_code', 'mobile_number')},
            },
        ),
    ]
