# Generated by Django 4.1.5 on 2025-01-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
