# Generated by Django 4.2.7 on 2025-01-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_user_city_user_state_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=999, unique=True),
        ),
    ]
