# Generated by Django 4.1.5 on 2025-01-02 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmaceutical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=999)),
                ('description', models.TextField(max_length=999)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=999, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PharmaceuticalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='Pharmaceutical/%Y-%m/')),
                ('file_type', models.CharField(choices=[('Profile Image', 'Profile Image'), ('License', 'License')], default='Profile Image', max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_watermark_added', models.BooleanField(default=False)),
                ('pharmaceutical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmaceutical_media', to='Pharmaceutical.pharmaceutical')),
            ],
        ),
    ]
