# Generated by Django 4.1.5 on 2023-07-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatXpo', '0002_xpochat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_query',
            field=models.TextField(default='', verbose_name='User Question to AI'),
        ),
    ]
