# Generated by Django 4.1.5 on 2023-07-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatXpo', '0003_chatmessage_user_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_output_urdu',
            field=models.TextField(default=''),
        ),
    ]
