# Generated by Django 4.1.5 on 2024-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatXpo', '0004_chatmessage_user_output_urdu'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='openai_msg_type',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('system', 'system')], default='user', max_length=50),
        ),
    ]
