# Generated by Django 4.1.5 on 2024-06-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatXpo', '0005_chatmessage_openai_msg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='openai_msg_type',
            new_name='role',
        ),
    ]
