# Generated by Django 4.1.5 on 2024-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatXpo', '0006_rename_openai_msg_type_chatmessage_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user_query',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='display_content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='extracted_info',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user_output_urdu',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='answer',
            field=models.TextField(default='', verbose_name='AI Bot Reply'),
        ),
    ]
