# Generated by Django 4.1.5 on 2024-06-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatXpo', '0007_rename_user_query_chatmessage_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='content',
        ),
    ]
