# Generated by Django 4.1.5 on 2024-07-21 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChat',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_users', models.ManyToManyField(related_name='allowed_video_chats', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_chats', to=settings.AUTH_USER_MODEL)),
                ('paticipants', models.ManyToManyField(blank=True, related_name='participated_video_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoChatSetting',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('lock_meeting', models.BooleanField(default=False)),
                ('waiting_room', models.BooleanField(default=True)),
                ('share_screen', models.BooleanField(default=False)),
                ('allow_chat', models.BooleanField(default=False)),
                ('unmute', models.BooleanField(default=False)),
                ('start_video', models.BooleanField(default=False)),
                ('allow_rename', models.BooleanField(default=False)),
                ('muted_participant', models.ManyToManyField(related_name='muted_participants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vchat_settings', to=settings.AUTH_USER_MODEL)),
                ('video_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chat_settings', to='Meet.videochat')),
            ],
        ),
        migrations.CreateModel(
            name='VideoChatMedia',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='video_chat_media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vchat_medias', to=settings.AUTH_USER_MODEL)),
                ('video_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chat_medias', to='Meet.videochat')),
            ],
        ),
    ]
