# Generated by Django 4.1.5 on 2023-02-12 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('svg_icon', models.TextField()),
                ('color_code', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='specialities/images/')),
            ],
        ),
    ]
