# Generated by Django 4.1.5 on 2023-02-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Specility', 'verbose_name_plural': 'Specilities'},
        ),
    ]
