# Generated by Django 4.1.5 on 2023-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0002_alter_speciality_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speciality',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
