# Generated by Django 4.1.5 on 2023-02-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0003_speciality_is_active_speciality_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
