# Generated by Django 4.1.5 on 2023-02-18 16:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0005_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('svg_icon', models.TextField()),
                ('color_code', models.CharField(default='', max_length=10)),
                ('description', models.TextField(default='')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='country/flags/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('svg_icon', models.TextField()),
                ('color_code', models.CharField(default='', max_length=10)),
                ('description', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_states', to='Trauma.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=500)),
                ('svg_icon', models.TextField()),
                ('color_code', models.CharField(default='', max_length=10)),
                ('description', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_cities', to='Trauma.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_cities', to='Trauma.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
