# Generated by Django 4.1.5 on 2023-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0006_country_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
