# Generated by Django 4.1.5 on 2023-03-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0007_country_dial_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='random_files/images/')),
            ],
        ),
    ]
