# Generated by Django 4.1.5 on 2023-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0009_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='slug',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='disease',
            name='tag_line',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='speciality',
            name='slug',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='speciality',
            name='tag_line',
            field=models.CharField(default='', max_length=800),
        ),
    ]
