# Generated by Django 4.1.5 on 2023-07-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0010_disease_slug_disease_tag_line_speciality_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='otp_type',
            field=models.CharField(default='', max_length=999),
        ),
    ]
