# Generated by Django 4.1.5 on 2024-06-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0011_verificationcode_otp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speciality_diseases', to='Trauma.speciality'),
        ),
    ]
