# Generated by Django 4.1.5 on 2024-06-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0012_disease_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='speciality_type',
            field=models.CharField(default='', max_length=999),
        ),
    ]
