# Generated by Django 4.1.5 on 2024-07-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0013_speciality_speciality_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='mobile_number',
            field=models.CharField(default='', max_length=999),
        ),
    ]
