# Generated by Django 4.1.5 on 2025-01-11 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0014_verificationcode_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
