# Generated by Django 4.2.7 on 2025-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0017_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_to_text/')),
                ('text', models.TextField(default='')),
                ('data', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
