# Generated by Django 4.1.5 on 2023-07-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0004_alter_profile_profile_type'),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=999)),
                ('street_address', models.TextField(default='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_locations', to='Hospital.hospital')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_hospital_locations', to='Profile.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_type', models.CharField(choices=[('EMAIL', 'EMAIL'), ('PHONE_NUMBER', 'PHONE_NUMBER')], default='EMAIL', max_length=50)),
                ('contact_title', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('dial_code', models.CharField(default='', max_length=20)),
                ('mobile_number', models.CharField(default='', max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_location_contacts', to='Hospital.hospital')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_contacts', to='Hospital.hospitallocation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_hospital_location_contacts', to='Profile.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_location_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_type', models.CharField(choices=[('Profile Image', 'Profile Image'), ('CNIC Front', 'CNIC Front'), ('CNIC Back', 'CNIC Back'), ('License', 'License')], default='Profile Image', max_length=30)),
                ('file', models.FileField(upload_to='Hospital/Files/%Y-%m')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_medias', to='Hospital.hospital')),
            ],
        ),
    ]
