# Generated by Django 4.1.5 on 2023-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_hospitallocation_locationcontact_hospitalmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'HealthCare Facility, Hospital or Private Clinic'},
        ),
        migrations.AlterField(
            model_name='hospital',
            name='facility_type',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Private_Clinic', 'Private_Clinic')], default='Hospital', max_length=50),
        ),
    ]
