# Generated by Django 4.1.5 on 2024-06-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trauma', '0013_speciality_speciality_type'),
        ('Hospital', '0005_hospital_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitallocation',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_hospital_locations', to='Trauma.city'),
        ),
        migrations.AddField(
            model_name='hospitallocation',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_hospital_locations', to='Trauma.country'),
        ),
        migrations.AddField(
            model_name='hospitallocation',
            name='state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_hospital_locations', to='Trauma.state'),
        ),
    ]
