# Generated by Django 4.1.5 on 2024-07-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_hospitallocation_city_hospitallocation_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcontact',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='locationcontact',
            name='user',
        ),
        migrations.AddField(
            model_name='hospital',
            name='fee',
            field=models.FloatField(default=0.0, verbose_name='Platform Service Fee(%)'),
        ),
    ]
