# Generated by Django 4.1.5 on 2024-07-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_remove_locationcontact_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitallocation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='hospitallocation',
            name='user',
        ),
        migrations.AlterField(
            model_name='locationcontact',
            name='email',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='locationcontact',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
