# Generated by Django 4.1.5 on 2024-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_hospitalmedia_is_watermark_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.TextField(default=''),
        ),
    ]
