# Generated by Django 4.1.5 on 2024-12-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0012_hospital_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcontact',
            name='location',
            field=models.ForeignKey(help_text='Select Location for this Hospital', on_delete=django.db.models.deletion.PROTECT, related_name='location_contacts', to='Hospital.hospitallocation'),
        ),
    ]
