# Generated by Django 4.1.5 on 2025-01-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0013_alter_locationcontact_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999)),
                ('phone', models.CharField(default='', max_length=999)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
