# Generated by Django 4.1.5 on 2024-05-31 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_alter_hospital_facility_type'),
        ('Doctor', '0004_alter_doctor_profile_alter_doctor_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslots',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_timeslots', to='Hospital.hospital'),
        ),
    ]
