# Generated by Django 4.1.5 on 2024-05-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_doctortimeslots_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslots',
            name='availability_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Hospital', 'Hospital')], default='Online', max_length=20),
        ),
    ]
