# Generated by Django 4.1.5 on 2024-05-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_doctortimeslots_availability_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor24by7',
            options={'verbose_name': 'Doctor Availability in Emergency'},
        ),
        migrations.AlterModelOptions(
            name='doctoronlineavailability',
            options={'verbose_name': 'Doctor Available Days'},
        ),
        migrations.AlterModelOptions(
            name='doctortimeslots',
            options={'verbose_name': 'Doctor Availability + Fee (Hospital | Online)'},
        ),
    ]
