# Generated by Django 4.1.5 on 2024-05-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_alter_doctor24by7_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
