# Generated by Django 4.1.5 on 2024-05-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_alter_hospital_facility_type'),
        ('Doctor', '0008_doctor_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslots',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_timeslots', to='Hospital.hospitallocation'),
        ),
        migrations.AlterField(
            model_name='doctortimeslots',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_timeslots', to='Hospital.hospital'),
        ),
    ]
