# Generated by Django 4.1.5 on 2024-05-31 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_alter_hospital_facility_type'),
        ('Doctor', '0009_doctortimeslots_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctortimeslots',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctortimeslots',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctortimeslots',
            name='location',
        ),
        migrations.CreateModel(
            name='DoctorWithHospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_timeslots', to='Doctor.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_timeslots', to='Hospital.hospital')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_timeslots', to='Hospital.hospitallocation')),
            ],
        ),
        migrations.AddField(
            model_name='doctortimeslots',
            name='doc_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_hospital_timeslots', to='Doctor.doctorwithhospital'),
        ),
    ]
