# Generated by Django 4.1.5 on 2024-05-31 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0011_doctortimeslots_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('speciality', models.CharField(default='', max_length=999)),
                ('practice_institute', models.CharField(default='', max_length=999)),
                ('docs', models.FileField(blank=True, null=True, upload_to='doctor_experience/docs/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_experiences', to='Doctor.doctor')),
            ],
        ),
    ]
