# Generated by Django 4.1.5 on 2024-05-31 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_doctoreducation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoreducation',
            name='practice_institute',
        ),
        migrations.AddField(
            model_name='doctoreducation',
            name='degree_type',
            field=models.CharField(choices=[('Master', 'Master'), ('MBBS', 'MBBS'), ('MD', 'MD'), ('Diploma', 'Diploma'), ('Other', 'Other')], default='', max_length=999),
        ),
        migrations.AddField(
            model_name='doctoreducation',
            name='institute',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='doctoreducation',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='doctor_education/docs/'),
        ),
        migrations.AlterField(
            model_name='doctoreducation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_education', to='Doctor.doctor'),
        ),
        migrations.CreateModel(
            name='DoctorExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('speciality', models.CharField(default='', max_length=999)),
                ('practice_institute', models.CharField(default='', max_length=999)),
                ('docs', models.FileField(blank=True, null=True, upload_to='doctor_experience/docs/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_experiences', to='Doctor.doctor')),
            ],
        ),
    ]
