# Generated by Django 4.1.5 on 2024-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0016_doctorquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslots',
            name='title',
            field=models.CharField(default='', max_length=999),
        ),
    ]
