# Generated by Django 4.1.5 on 2024-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_doctortimeslots_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.CharField(default='', max_length=999),
        ),
    ]
