# Generated by Django 4.1.5 on 2024-07-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0019_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorwithhospital',
            name='phone',
            field=models.CharField(default='', max_length=999),
        ),
    ]
