# Generated by Django 4.1.5 on 2024-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0020_doctorwithhospital_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile_number',
            field=models.CharField(default='', max_length=20, verbose_name='Doctor Personal Number'),
        ),
    ]
