# Generated by Django 4.1.5 on 2024-07-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0021_alter_doctor_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorwithhospital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorwithhospital',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorwithhospital',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorwithhospital',
            name='is_hospital_informed',
            field=models.BooleanField(default=False),
        ),
    ]
