# Generated by Django 4.1.5 on 2024-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0024_alter_doctor_working_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorwithhospital',
            name='phone',
            field=models.CharField(default='', help_text='Number for the doctor’s PA or hospital contact for appointment confirmations.', max_length=999),
        ),
    ]
