# Generated by Django 4.1.5 on 2024-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0025_alter_doctorwithhospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pmdc_id',
            field=models.CharField(default='', max_length=999),
        ),
    ]
