# Generated by Django 4.1.5 on 2024-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0026_doctor_pmdc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormedia',
            name='is_watermark_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctormedia',
            name='file',
            field=models.FileField(help_text='Whenever change Image, You must uncheck "Is Watermark Added"', upload_to='Doctor/Files/%Y-%m'),
        ),
    ]
