# Generated by Django 4.2.7 on 2025-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0029_doctorrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoreducation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoreducation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
