# Generated by Django 4.2.7 on 2025-01-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0030_alter_doctoreducation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='', max_length=999),
        ),
    ]
