# Generated by Django 4.1.5 on 2023-07-18 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Secure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=999)),
                ('name', models.CharField(default='', max_length=225)),
                ('email', models.CharField(default='', max_length=225)),
                ('rating', models.FloatField(default=0)),
                ('text', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_application_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
