# Generated by Django 4.1.5 on 2024-06-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0004_chatinstructions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpokey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='xpokey',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xpokey',
            name='token_used',
            field=models.IntegerField(default=0),
        ),
    ]
