# Generated by Django 4.1.5 on 2024-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0005_xpokey_is_active_xpokey_is_deleted_xpokey_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpokey',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xpokey',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
