# Generated by Django 4.1.5 on 2024-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0006_xpokey_completion_tokens_xpokey_prompt_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpokey',
            name='total_requests',
            field=models.IntegerField(default=0),
        ),
    ]
