# Generated by Django 4.1.5 on 2024-07-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0007_xpokey_total_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationreview',
            name='phone_number',
            field=models.CharField(default='', max_length=999),
        ),
    ]
