# Generated by Django 4.1.5 on 2024-08-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0008_applicationreview_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraumacareApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999)),
                ('version', models.CharField(default='', max_length=999)),
                ('file', models.FileField(upload_to='trauma_app')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
