# Generated by Django 4.1.5 on 2024-08-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0009_traumacareapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traumacareapp',
            old_name='file',
            new_name='android',
        ),
    ]
