# Generated by Django 4.1.5 on 2024-08-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0010_rename_file_traumacareapp_android'),
    ]

    operations = [
        migrations.AddField(
            model_name='traumacareapp',
            name='ios',
            field=models.FileField(blank=True, null=True, upload_to='trauma_app'),
        ),
    ]
