# Generated by Django 4.1.5 on 2025-01-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_shipingaddress_is_deleted'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_address_orders', to='Profile.shipingaddress'),
        ),
    ]
