# Generated by Django 4.1.5 on 2025-01-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_price',
            field=models.FloatField(default=0),
        ),
    ]
