# Generated by Django 4.2.7 on 2025-01-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_orderproductreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductreview',
            name='parent_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_reviews', to='Order.orderproductreview'),
        ),
    ]
